### ISSUE TITLE
Proposal for simplifying build system

### ISSUE THREAD

**Issue by hamstu** [bufferapp/ui#267]
### Overview

I propose we change the build system for `@bufferapp/ui` to use **Rollup**, remove the generated docs site, and switch to Storybook for component documentation. 

📹  **[Watch video overview](https://www.loom.com/share/7b5b21ed46b74281a91a6b6820c68589)** (10 min)

---

### 🗞️ Move to Rollup

[Rollup](https://rollupjs.org/guide/en/) is popular module bundler most commonly used for packaging libraries. Right now in `@bufferapp/ui` we use Babel by itself to transpile the source code into CommonJS and then Publish on NPM. Rollup won't replace Babel, as it is a tool which, like webpack, uses Babel to transpile and then produce a bundled file.

It's highly configurable, but also very simple, which allows for a lot of control for library authors. For example, it's trivial to produce two builds; your classic CommonJS version (`const foo = require('foo')`) and an ES Modules version (`import foo from 'foo'`). **The latter when processed by webpack makes it easier for our apps to do tree-shaking / dead code elimination; i.e., smaller bundles!**

Many well known 3rd party libraries are bundled with Rollup (Vue, Ember, Preact, D3, Three.js, Moment, and many more) and so I believe we'll also greatly benefit from the community knowledge and support here. 

### 🗑️  Remove the BDS documentation

With [BDS documentation being moved into Notion](https://www.notion.so/buffer/The-Great-Documentation-Migration-ff0abc2edabe4b84bb41907234494307), we no longer need to build or maintain [our own copy](https://bufferapp.github.io/ui/#/ui/ui/ui) in this library. The code for this custom-built documentation system – while very powerful – is very complex in code and configuration. By removing it we can reduce cognitive load on engineers and focus more on building and packaging a best-in-class component library.

Once removed I propose we use [Storybook](https://storybook.js.org/). Storybook has matured a lot over the last few years and I think it will easily meet our needs for component building / testing, as well as developer-focused documentation. A script could likely be written to transform existing documentation files to the Storybook 'stories' format, making the migration easier.

Same as the current docs site, we could have the Storybook automatically deployed via Github Pages to the BDS site URL.

### Improved Testing

This might be more of a nice-to-have, but I also love [React Testing Library](https://testing-library.com/) (props to @MayaUribe for introducing that in Publish). Some of our current tests are focused very much on [testing implementation details](https://github.com/bufferapp/ui/blob/42881db8b9bd070e51155909ca7716eefea2eb94/src%2Fcomponents%2FSelect%2FSelect.test.js#L22) and could be improved with [a better approach](https://kentcdodds.com/blog/testing-implementation-details).

### [Spike] Proof of concept

I did a quick spike on bundling `@bufferapp/ui` with Rollup, which you can see here if you're interested: https://github.com/bufferapp/ui-proposal

**Comment by gmzjuliana** [comment]
hey @hamstu thanks for putting this together 🌮 I love your proposal, it sounds like it addresses a lot of pain points we currently face (the bundling, inability to tree shake, document website and minimal testing) and super elegantly too! I was just checking out the new versions of storybook the other day and I'd be excited to use it for this 😄 For the testing, I think there are quite a few fans of react testing library on the team so keen to check it out as well!

I wish I had some questions or things to add but this is all very complete 🎉

**Comment by MayaUribe** [comment]
Hi there @hamstu!

First off, I love the way you laid out this proposal over here! 🤩 I'll copy this format in the future 😂

I really like your proposal overall, +1 to all that @gmzjuliana said, I love the idea of using storybook, and as you mentioned in the video, the latest versions have lots of new and very useful features, we can potentially test more things as we build components by using the addons, like [a11y](https://github.com/storybookjs/storybook/tree/master/addons/a11y) and coming from Publish where we use it, I can really see the value of adding it, especially if we are moving the documentation to Notion.

And last but not least, testing 🐙🧪
⚡️ YES! ⚡️ I think this repo it's an ideal candidate to use react-testing-library because it's a strictly component-based project -we don't handle stores- and it would be extremely straightforward to start testing. Because this is a project consumed by all our products having good tests here is a great one to have.

🚀
